import type { Artwork } from "./types";

/**
 * Fallback artwork shown only when Supabase is not configured.
 * Images and metadata sourced from @ellawright.art on Instagram.
 * Once Supabase is connected, upload via /admin to replace this data.
 */
const now = "2026-06-11T21:36:17.516Z";

export const SAMPLE_ARTWORKS: Artwork[] = [
  {
    id: "1",
    title: "Alpha and Omega",
    slug: "alpha-and-omega",
    category: "spiritual",
    medium: "Oil on Wood Panel",
    size: "7\" x 7\"",
    year: 2026,
    description: "",
    image_url: "/artwork/alpha-and-omega.jpg",
    image_alt: "Alpha and Omega — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "2",
    title: "Sharing Truth No Other Way",
    slug: "sharing-truth-no-other-way",
    category: "spiritual",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2025,
    description: "With one bite of the fruit Eve gave the world the ability to decipher good from evil.",
    image_url: "/artwork/sharing-truth-no-other-way.jpg",
    image_alt: "Sharing Truth No Other Way — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "3",
    title: "Worshipping the Living Water",
    slug: "worshipping-the-living-water",
    category: "spiritual",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2025,
    description: "",
    image_url: "/artwork/worshipping-the-living-water.jpg",
    image_alt: "Worshipping the Living Water — original painting by Ella Wright",
    object_position: "center 30%",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "4",
    title: "Brother of Jared",
    slug: "brother-of-jared",
    category: "spiritual",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2024,
    description: "",
    image_url: "/artwork/brother-of-jared.jpg",
    image_alt: "Brother of Jared — original painting by Ella Wright",
    object_position: "center 35%",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "5",
    title: "Supported on all Sides",
    slug: "supported-on-all-sides",
    category: "spiritual",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2024,
    description: "We are never alone throughout our successes, challenges, and mistakes. We have an infinite cheering squad in the angels around us and receive loving support from our Heavenly Parents as well as our loved ones on earth.",
    image_url: "/artwork/supported-on-all-sides.jpg",
    image_alt: "Supported on all Sides — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 5,
    created_at: now,
    updated_at: now,
  },
  {
    id: "6",
    title: "Yearn to Learn",
    slug: "yearn-to-learn",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2024,
    description: "I painted this after finishing a research paper on the effects of controversial literature. The figures made from the book pages represent empathy, culture, exploration, diversity, discovery, and critical thinking. Reading can be a powerful source of learning to understand the perspectives of the people living beside us.",
    image_url: "/artwork/yearn-to-learn.jpg",
    image_alt: "Yearn to Learn — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 6,
    created_at: now,
    updated_at: now,
  },
  {
    id: "7",
    title: "Benefactor of Pioneer Greatness",
    slug: "benefactor-of-pioneer-greatness",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2023,
    description: "My great grandmother always said, “You come from pioneer stock!” And she passed that down to her daughter and now my mom says it to me. I come from a heritage of strong women. This piece embodies the greatness we pass from one generation to another. My heritage includes a strong 52 year old woman who left Europe, traveled thousands of miles on foot on her own, and built a new world for her family. I am a part of that new world, full of opportunities and privilege as a result of her strength.",
    image_url: "/artwork/benefactor-of-pioneer-greatness.jpg",
    image_alt: "Benefactor of Pioneer Greatness — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 7,
    created_at: now,
    updated_at: now,
  },
  {
    id: "8",
    title: "Heavenly Hands",
    slug: "heavenly-hands",
    category: "spiritual",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2024,
    description: "Heavenly Hands is a celebration of the divine within womanhood—the sacredness of nurturing life, the quiet strength found in surrender, and the beauty that blossoms in love.\n\nThrough soft brushstrokes and radiant color, this piece honors the tender power of mothers—held by grace, guided by faith, and wrapped in the light of something greater.",
    image_url: "/artwork/heavenly-hands.jpg",
    image_alt: "Heavenly Hands — oil painting by Ella Wright",
    object_position: "center 32%",
    is_available: false,
    is_featured: true,
    show_on_home: true,
    display_order: 8,
    created_at: now,
    updated_at: now,
  },
  {
    id: "9",
    title: "Hello There",
    slug: "hello-there",
    category: "spiritual",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2023,
    description: "",
    image_url: "/artwork/hello-there.jpg",
    image_alt: "Hello There — original painting by Ella Wright",
    object_position: "center 30%",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 9,
    created_at: now,
    updated_at: now,
  },
  {
    id: "10",
    title: "Making Waves",
    slug: "making-waves",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2023,
    description: "",
    image_url: "/artwork/making-waves.jpg",
    image_alt: "Making Waves — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 10,
    created_at: now,
    updated_at: now,
  },
  {
    id: "11",
    title: "Perspective",
    slug: "perspective",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2023,
    description: "We each bring our own perspectives, gifts, and color into the world. There is a reason we do not see in black and white. Connecting with each other brings beauty and strength.",
    image_url: "/artwork/perspective.jpg",
    image_alt: "Perspective — original painting by Ella Wright",
    object_position: "center 40%",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 11,
    created_at: now,
    updated_at: now,
  },
  {
    id: "12",
    title: "Prying Piglet",
    slug: "prying-piglet",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2023,
    description: "",
    image_url: "/artwork/prying-piglet.jpg",
    image_alt: "Prying Piglet — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 12,
    created_at: now,
    updated_at: now,
  },
  {
    id: "13",
    title: "The Woman at the Well",
    slug: "the-woman-at-the-well",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2023,
    description: "",
    image_url: "/artwork/the-woman-at-the-well.jpg",
    image_alt: "The Woman at the Well — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 13,
    created_at: now,
    updated_at: now,
  },
  {
    id: "14",
    title: "The Woman With the Issue of Blood",
    slug: "the-woman-with-the-issue-of-blood",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2023,
    description: "",
    image_url: "/artwork/the-woman-with-the-issue-of-blood.jpg",
    image_alt: "The Woman With the Issue of Blood — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 14,
    created_at: now,
    updated_at: now,
  },
  {
    id: "15",
    title: "Captain",
    slug: "captain",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/captain.jpg",
    image_alt: "Captain — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 15,
    created_at: now,
    updated_at: now,
  },
  {
    id: "16",
    title: "Coyote",
    slug: "coyote",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/coyote.jpg",
    image_alt: "Coyote — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 16,
    created_at: now,
    updated_at: now,
  },
  {
    id: "17",
    title: "Creation",
    slug: "creation",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "I like to think that we helped God during the creation. This digital artwork shows a pre-mortal spirit watching and helping as God sculpts her face.",
    image_url: "/artwork/creation.jpg",
    image_alt: "Creation — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 17,
    created_at: now,
    updated_at: now,
  },
  {
    id: "18",
    title: "Esther",
    slug: "esther",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "Esther has been my favorite scripture story since I was little.",
    image_url: "/artwork/esther.jpg",
    image_alt: "Esther — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 18,
    created_at: now,
    updated_at: now,
  },
  {
    id: "19",
    title: "Gerald",
    slug: "gerald",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/gerald.jpg",
    image_alt: "Gerald — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 19,
    created_at: now,
    updated_at: now,
  },
  {
    id: "20",
    title: "Go in Peace",
    slug: "go-in-peace",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/go-in-peace.jpg",
    image_alt: "Go in Peace — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 20,
    created_at: now,
    updated_at: now,
  },
  {
    id: "21",
    title: "Goldendoodle",
    slug: "goldendoodle",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/goldendoodle.jpg",
    image_alt: "Goldendoodle — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 21,
    created_at: now,
    updated_at: now,
  },
  {
    id: "22",
    title: "Happy pig",
    slug: "happy-pig",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "Animals in color are always better!",
    image_url: "/artwork/happy-pig.jpg",
    image_alt: "Happy pig — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 22,
    created_at: now,
    updated_at: now,
  },
  {
    id: "23",
    title: "Heavenly Mother",
    slug: "heavenly-mother",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "This is how I imagine Heavenly Mother.",
    image_url: "/artwork/heavenly-mother.jpg",
    image_alt: "Heavenly Mother — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 23,
    created_at: now,
    updated_at: now,
  },
  {
    id: "24",
    title: "House of the Lord",
    slug: "house-of-the-lord",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "Inspired by President Thomas S. Monson's promise: \"I know your lives are busy. I know that you have much to do. But I make you a promise that if you will go to the house of the Lord, you will be blessed; life will be better for you.\"",
    image_url: "/artwork/house-of-the-lord.jpg",
    image_alt: "House of the Lord — original painting by Ella Wright",
    object_position: "center 25%",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 24,
    created_at: now,
    updated_at: now,
  },
  {
    id: "25",
    title: "Let him in",
    slug: "let-him-in",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/let-him-in.jpg",
    image_alt: "Let him in — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 25,
    created_at: now,
    updated_at: now,
  },
  {
    id: "26",
    title: "Mary and Jesus",
    slug: "mary-and-jesus",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/mary-and-jesus.jpg",
    image_alt: "Mary and Jesus — original painting by Ella Wright",
    object_position: "center 20%",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 26,
    created_at: now,
    updated_at: now,
  },
  {
    id: "27",
    title: "Meek",
    slug: "meek",
    category: "spiritual",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/meek.jpg",
    image_alt: "Meek — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 27,
    created_at: now,
    updated_at: now,
  },
  {
    id: "28",
    title: "Peeking in",
    slug: "peeking-in",
    category: "spiritual",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/peeking-in.jpg",
    image_alt: "Peeking in — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 28,
    created_at: now,
    updated_at: now,
  },
  {
    id: "29",
    title: "Quail",
    slug: "quail",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/quail.jpg",
    image_alt: "Quail — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 29,
    created_at: now,
    updated_at: now,
  },
  {
    id: "30",
    title: "Rainbow Cow",
    slug: "rainbow-cow",
    category: "landscapes",
    medium: "Acrylic",
    size: "24\" x 30\"",
    year: 2022,
    description: "",
    image_url: "/artwork/rainbow-cow.jpg",
    image_alt: "Rainbow Cow — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 30,
    created_at: now,
    updated_at: now,
  },
  {
    id: "31",
    title: "Rainbow Sloth",
    slug: "rainbow-sloth",
    category: "landscapes",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "I love rainbow animals!!!",
    image_url: "/artwork/rainbow-sloth.jpg",
    image_alt: "Rainbow Sloth — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 31,
    created_at: now,
    updated_at: now,
  },
  {
    id: "32",
    title: "The Service Quilt",
    slug: "the-service-quilt",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "This painting shows an older woman teaching a girl to sew. Each pattern block represents a different way to serve others. In my life I have been taught by my parents, grandparents, teachers, and youth leaders how to serve and the joy it brings.",
    image_url: "/artwork/the-service-quilt.jpg",
    image_alt: "The Service Quilt — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 32,
    created_at: now,
    updated_at: now,
  },
  {
    id: "33",
    title: "Trying To Be Like Him",
    slug: "trying-to-be-like-him",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "The animals following Jesus represent his traits. The little boy is working hard to imitate these.",
    image_url: "/artwork/trying-to-be-like-him.jpg",
    image_alt: "Trying To Be Like Him — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 33,
    created_at: now,
    updated_at: now,
  },
  {
    id: "34",
    title: "You Are Not Alone",
    slug: "you-are-not-alone",
    category: "women-motherhood",
    medium: "Oil on Canvas",
    size: "24\" x 30\"",
    year: 2022,
    description: "He opened his call to discover where he would be assigned to serve a two year religious mission. He’s assigned to the same mission as his grandpa who passed before he was born. How ever present God’s hand is in the details of our lives. We are not alone.",
    image_url: "/artwork/you-are-not-alone.jpg",
    image_alt: "You Are Not Alone — original painting by Ella Wright",
    object_position: "center center",
    is_available: false,
    is_featured: false,
    show_on_home: false,
    display_order: 34,
    created_at: now,
    updated_at: now,
  },
];
